#!/bin/bash

# +--------+
# | System |
# +--------+

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias path='echo $PATH | tr -s ":" "\n"' # Pretty print the path

# +-----+
# | Zsh |
# +-----+

# Every directory visited will populate the stack
# The alias d will display directories prefixed with a number
# Just type this number to go straight to that directory
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index # directory stack

# zoxide
alias j='z'
alias f='zi'


# +-----+
# | Apt |
# +-----+
alias sup='sudo apt update && sudo apt upgrade -y' # update & upgrade

# +------+
# | Core |
# +------+
alias cp='cp -iv'         # Confirm before overwriting something
alias rm='rm -i'
alias mv='mv -iv'
alias df='df -h'          # Human-readable sizes
alias free='free -m'   # Show sizes in MB
alias chmod="chmod -v"

# +---------+
# | Folders |
# +---------+
alias doc="$HOME/Documents"
alias dow="$HOME/Downloads"
alias dot="$HOME/.dotfiles"
alias desk="/mnt/c/Users/Gordon/Desktop"
alias windown="/mnt/d"

# +------+
# | grep |
# +------+
# Colorize grep output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias zedit='nvim ~/.config/zsh/.zshrc'

# +-----+
# | Git |
# +-----+
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' # for dotfiles

# +----------------+
# | Docker-Compose |
# +----------------+
alias dc='docker-compose '

# +--------+
# | Global |
# +--------+
# Type letter, then space, ie "ls- al T[space]" will become "ls -al | tail"
alias -g L='| less'
alias -g G='| rg '
# alias -g G='| egrep --color'
alias -g S='| sort'
alias -g R='| sort -rn'
alias -g H='| head'
alias -g T='| tail'
