#!/bin/zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

fpath=($ZDOTDIR/plugins $fpath)

setopt nobeep               	# No Beeping
setopt CORRECT            	# Spellcheck
setopt NO_FLOW_CONTROL      	# disable start/stop chars in shell editor (^S, ^Q)
setopt interactivecomments  	# Allows comments on the command line

# Don't treat non-executable files in your $path as commands.
# This makes sure they don't show up as command completions.
setopt HASH_EXECUTABLES_ONLY

# +------------+
# | NAVIGATION |
# +------------+

setopt AUTO_CD                  # Go to folder path without using cd.

setopt AUTOPUSHD                # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS        # Do not store duplicates in the stack.
setopt PUSHD_SILENT             # Do not print the directory stack after pushd or popd.

setopt CDABLE_VARS              # Change directory to a path stored in a variable.
setopt EXTENDED_GLOB            # Use extended globbing syntax.

# Create shortcuts for your favorite directories.
# Set these early, because it affects how dirs are displayed and printed.
hash -d ZSH=$ZDOTDIR/
hash -d NVIM=$XDG_CONFIG_HOME/nvim/

# +---------+
# | HISTORY |
# +---------+

setopt EXTENDED_HISTORY         # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY            # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST   # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS         # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS     # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS        # Do not display a previously found event.
setopt HIST_IGNORE_SPACE        # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS        # Do not write a duplicate event to the history file.
setopt HIST_VERIFY              # Do not execute immediately upon history expansion.
setopt HIST_FCNTL_LOCK          # Use modern file-locking mechanisms, for better safety & performance.

# +------------------------+
# | Colours / Prompt Theme |
# +------------------------+
source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme
export LS_COLORS="$(vivid generate catppuccin-macchiato)"


# +------------+
# | COMPLETION |
# +------------+
# zstyle ':autocomplete:*' widget-style menu-complete
# source ~/.config/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# zstyle ':autocomplete:*' insert-unambiguous yes
# zstyle ':autocomplete:*' fzf-completion yes

source $ZDOTDIR/completion.zsh
autoload -U select-word-style
select-word-style bash
# +-----------------+
# | AUTOSUGGESTIONS |
# +----------------+
source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


# +---------+
# | ALIASES |
# +---------+

source $ZDOTDIR/aliases.zsh

# +----------+
# | KEYBINDS |
# +----------+

source $ZDOTDIR/keybinds.zsh

# +-----------+
# | FUNCTIONS |
# +-----------+

source $ZDOTDIR/functions.zsh

# +--------+
# | ZOXIDE |
# +--------+
eval "$(zoxide init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /home/gordon/.config/broot/launcher/bash/br

# +--------+
# | PYTHON |
# +--------+
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# +-----------------------+
# | ZSH-SYNTAX-HIGHLIGHT |
# +----------------------+
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
